spring:
  application:
    name: zhymgc-consumer
server:
  port: 9001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/

feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /

